[package]
name = "chat-gipity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.3"
openai = "1.0.0-alpha.8"
tokio = { version = "1.27.0", features = ["full"] }
